### ISSUE TITLE
node-fetch missing in the dependency list

### ISSUE THREAD

**Issue by onichandame** [ipfs/js-ipfs-utils#148]
### Problem

This lib requires `native-fetch` which declares `node-fetch` as its peerDep. But `node-fetch` is not in the deps list of this lib. Should we expect the app that requires this lib to install `node-fetch` or should we add `node-fetch` to this lib's deps list?

*Disclaimer: I did not require this lib directly but installed it when using `ipfs`. So I am not sure at which level in the dependency tree should we add `node-fetch` as a direct dependency. I am asking here because this lib directly requires `native-fetch`*

**Comment by achingbrain** [comment]
`node-fetch` is declared as a dependency of this module [here](https://github.com/ipfs/js-ipfs-utils/blob/master/package.json#L65).

What is the problem you are seeing?

**Comment by lidel** [comment]
Assuming an older version was used and that caused the error. Please open a new issue if its still the case in the latest one.
