### ISSUE TITLE
`electron-fetch` dependency is not ESM compatible

### ISSUE THREAD

**Issue by TheDutchCoder** [ipfs/js-ipfs-utils#164]
This issue originated on the `js-ipfs` repo, where a bug was reported that the library wouldn't properly run with Vite, as `electron` somehow got required (https://github.com/ipfs/js-ipfs/issues/4011#issuecomment-1011102726).

After some diging, I found that `electron-fetch` is a dependency in this (js-ipfs-utils) library and that is a Node library, importing things like `url` and `http`, which are not usable in a browser.

I think for the ESM build of this package, `electron-fetch` shouldn't be included at all, but I'm not too familiar with how the different builds (in combination with environments) work.

**Comment by lidel** [comment]
Generic fix  / continued in https://github.com/ipfs/js-ipfs-utils/issues/154
