### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by yuanpli** [ipfs/js-ipfs-utils#225]
Node Version: 16.15.1

Error:
```
Error: [web3.storage@4.4.0 › ipfs-car@0.7.0 › ipfs-utils@9.0.9 › node-fetch@https://registry.npmjs.org/@achingbrain/node-fetch/-/node-fetch-2.6.7.tgz] Invalid Package, expected node-fetch but found @achingbrain/node-fetch
```
![image](https://user-images.githubusercontent.com/13729335/205797466-734b7737-6dd1-4bed-ad7a-68c6e3e70507.png)

Why add achingbrain/node-fetch as the dependency? It is a temporary fork of node-fetch. It will not be updated or maintained.

**Comment by achingbrain** [comment]
The fork has the fix from https://github.com/node-fetch/node-fetch/pull/1172 applied - as soon as that's released it can be removed and the regular node-fetch module used.

Please chime in on https://github.com/node-fetch/node-fetch/issues/1676 if you'd like to see that happen - it's out of our control.
