### ISSUE TITLE
[request] split or export functions that didn't export

### ISSUE THREAD

**Issue by bluelovers** [ipfs/js-ipfs-utils#28]
for example
https://github.com/ipfs/js-ipfs-utils/blob/master/src/files/normalise-input.js

export

- toFileObject
- toAsyncIterable
- ... others

that will help if wanna reuse function for make something
because copy/paste code for just wanna re-use it , is not funny

**Comment by achingbrain** [comment]
Most of these are pretty specific to normalising the input to `file.add` - do you have a specific use case in mind?

**Comment by bluelovers** [comment]
because i have issue with this
https://github.com/ipfs/js-ipfs/issues/2943

so i need make a new function for try avoid this happen

**Comment by achingbrain** [comment]
I'm not sure I understand how this would help.  Are you trying to reimplement bits of `ipfs.add`?

**Comment by bluelovers** [comment]
yes

**Comment by achingbrain** [comment]
In that case I'd just copy/paste the bits you need.

I don't think we should export or make available more than is necessary as it limits our ability to perform refactors or make other structural changes in the future.
