### ISSUE TITLE
Move http class into ipfs-http-client

### ISSUE THREAD

**Issue by achingbrain** [ipfs/js-ipfs-utils#32]
Do we use this anywhere else? Does it really need to be here? We need to do things that make it less of a general-purpose http request module like restrict it only to POST requests etc so I'm not sure it belongs here any more.

**Comment by achingbrain** [comment]
I think we actually use the http client in core so maybe don't remove this entirely, but can definitely have a non-generic http client for the http api client.

**Comment by hugomrdias** [comment]
im using it in aegir and ipfsd-ctl at least.. http-client uses a wrapper around it can't we just change that ?
