### ISSUE TITLE
node-fetch require breaks when bundling with webpack

### ISSUE THREAD

**Issue by dapplion** [ipfs/js-ipfs-utils#43]
The import in `http.js` of node-fetch breaks when bundling with webpack
https://github.com/ipfs/js-ipfs-utils/blob/c6337a9878c5aeb8f51a24f0f1707cb40925d8d2/src/http.js#L4

The issue is related to this thread https://github.com/node-fetch/node-fetch/issues/450 but it could be easily fixed by just doing
```js
const { default: fetch } = require('node-fetch')
```

**Comment by hugomrdias** [comment]
Need to check why js-ipfs doesn’t fail because of this.

**Comment by autonome** [comment]
Any update @hugomrdias ?

**Comment by hugomrdias** [comment]
This should be fixed now,.

Feel free to re open if this still happens.
