### ISSUE TITLE
HTTPOptions body type does not allow FormData

### ISSUE THREAD

**Issue by achingbrain** [ipfs/js-ipfs-utils#90]
The HTTPOptions type extends FetchOptions which extends RequestInit from `electron-fetch`, which has a body type of `Stream | string | Blob | Buffer | null` which does not include `FormData`.

In js-IPFS we transform multipart requests into FormData objects in the browser, which TS then says cannot be used with the http module exported by this module, since the types in `electron-fetch` say FormData is not a supported body type.

**Comment by lidel** [comment]
next steps are either:

- (a) PR electron-fetch
- (b) use types from something else
- (c) create our own types for fetch 


(b) seems to be preferred way to tackle this

**Comment by achingbrain** [comment]
Fixed by #129
